# Python

## Base Types

Binary, Octal and Hexa

In [1]:
b = 0b010
octal = 0o642
hexa = 0xF3
print(b, octal, hexa)

2 418 243


## Container types

List, tuples and dictionaries

In [4]:
list1 = [1, 0.2, "str"]
tuple1 = 11, "y", 7.4
tuple2 = (1,2,3)
dict1 = dict(a=1,b=2,c="v")
print(list1, tuple1, tuple2, dict1)

[1, 0.2, 'str'] (11, 'y', 7.4) (1, 2, 3) {'a': 1, 'b': 2, 'c': 'v'}


## Conversions

In [15]:
print(float("15.56"),"\n",
      chr(42),"\n",
      bytes([42]),"\n",
      list("abc"), "\n",
      dict([(3,"three"),(1,"one")]), "\n",
      "words with space".split(), "\n",
      "1,2,3,4".split(","), "\n",
      
     )



15.56 
 * 
 b'*' 
 ['a', 'b', 'c'] 
 {3: 'three', 1: 'one'} 
 ['words', 'with', 'space'] 
 ['1', '2', '3', '4'] 



## Sequence/Indexing

In [28]:
lst = [1, 2, 3, 4, 5]
print("lst[:-1]\t",lst[:-1],"\n",
      "lst[:3]\t",lst[:3],"\t\t", "exclusive here","\n",
      "lst[3:]\t",lst[3:],"\t\t", "inclusive here","\n",
      "lst[::-1]\t",lst[::-1],"\t", "start slice: end slice: step", "\n",
      )

lst[:-1]	 [1, 2, 3, 4] 
 lst[:3]	 [1, 2, 3] 		 exclusive here 
 lst[3:]	 [4, 5] 		 inclusive here 
 lst[::-1]	 [5, 4, 3, 2, 1] 	 start slice: end slice: step 



Deleting a few things within a list

In [29]:
del lst[3:5]
print(lst)
lst[0:2]=[9,9]
print(lst)

[1, 2, 3]
[9, 9, 3]


Math modules: math, fractions, numpy, etc

/  division
// integer division
%  remainder
** power

## Exceptions

In [30]:
try:
    1/0
except ZeroDivisionError:
    print("ZeroDivisionError Occurred")

ZeroDivisionError Occurred


## Generic operations

In [32]:
c=[5,4,3,2,1]
print("\n",len(c),"\n",sorted(c),"\n",)


 5 
 [1, 2, 3, 4, 5]


In [33]:
5 in c

True

In [38]:
for line, element in enumerate(c):
    print(line, element)

0 5
1 4
2 3
3 2
4 1


In [51]:
c.insert(5,6)
print(c)

[5, 4, 3, 2, 1, 6]


In [53]:
c.insert(0,7)
print(c)

[7, 5, 4, 3, 2, 1, 6, 0]


In [54]:
c.pop(7)
print(c)

[7, 5, 4, 3, 2, 1, 6]


In [58]:
dict1 = {'name':'John',
        'age': 40,
        'Job':'engineer',
        'hobby':'crossfit'}
print(dict1)
dict1.pop('age')

<built-in method items of dict object at 0x108197440>


40

In [59]:
print(dict1)

{'name': 'John', 'Job': 'engineer', 'hobby': 'crossfit'}


# Numpy

In [60]:
import numpy as np

In [61]:
print(np.arange(10,25,5))

[10 15 20]


In [63]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [103]:
a=np.random.random((3,2))
a

array([[0.77331545, 0.06416522],
       [0.40990642, 0.70405036],
       [0.70878564, 0.33803101]])

In [67]:
a.shape

(3, 2)

In [68]:
len(a)

3

In [69]:
a.ndim

2

In [70]:
a.size

6

In [72]:
b=np.array([[1,2],
          [3,4],
          [5,6]])
b.shape

(3, 2)

In [75]:
np.add(a,b)
np.exp(a)
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [76]:
b>2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [80]:
b.sum()
b.mean()

3.5

In [84]:
# deep copy
c=a.copy()
c[0][0]=0
c
a

array([[0.91389683, 0.58433831],
       [0.1241361 , 0.70514959],
       [0.19606775, 0.76038056]])

In [ ]:
# slicing, indexing

In [87]:
a[0,0]

0.9138968259636132

In [88]:
a[1,...]

array([0.1241361 , 0.70514959])

In [89]:
# reversed
a[::-1]

array([[0.19606775, 0.76038056],
       [0.1241361 , 0.70514959],
       [0.91389683, 0.58433831]])

In [91]:
# bolean indexing
a[a<0.6]

array([0.58433831, 0.1241361 , 0.19606775])

The question below was asked to one of my student but he/she/them had to use for loops instead

In [92]:
# transposing ()
np.transpose(a)

array([[0.91389683, 0.1241361 , 0.19606775],
       [0.58433831, 0.70514959, 0.76038056]])

In [93]:
# Flatten
a.ravel()

array([0.91389683, 0.58433831, 0.1241361 , 0.70514959, 0.19606775,
       0.76038056])

In [96]:
a.reshape(2,-1)

array([[0.91389683, 0.58433831, 0.1241361 ],
       [0.70514959, 0.19606775, 0.76038056]])

In [109]:
a

array([[0.77331545, 0.06416522],
       [0.40990642, 0.70405036],
       [0.70878564, 0.33803101]])

In [105]:
np.append([3,4,5],np.array([1, 2]))

array([3, 4, 5, 1, 2])

In [108]:
# delete second row of a
np.delete(a,1,axis=0)

array([[0.77331545],
       [0.40990642],
       [0.70878564]])

# Pandas

In [110]:
import pandas as pd

In [114]:
s=pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
s.head()

a    3
b   -5
c    7
d    4
dtype: int64

In [115]:
# Data frame
data = {'Country': ['Belgium', 'India', 'Brazil'],
       'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
       'Population': [1118485, 1387687867, 207465646]}
df = pd.DataFrame(data,
                 columns=['Country', 'Capital', 'Population'])

In [116]:
df.head()

Country    Capital  Population
0  Belgium   Brussels     1118485
1    India  New Delhi  1387687867
2   Brazil   Brasilia   207465646

In [117]:
s['b']

-5

In [118]:
df[1:]

Country    Capital  Population
1   India  New Delhi  1387687867
2  Brazil   Brasilia   207465646

In [124]:
df.iloc[[0],[2]]

Population
0     1118485

In [121]:
df.iloc[:,1]

0     Brussels
1    New Delhi
2     Brasilia
Name: Capital, dtype: object

In [125]:
df

Country    Capital  Population
0  Belgium   Brussels     1118485
1    India  New Delhi  1387687867
2   Brazil   Brasilia   207465646

In [132]:
df.loc[:,'Country']

0    Belgium
1      India
2     Brazil
Name: Country, dtype: object

In [133]:
s[s>2]

a    3
c    7
d    4
dtype: int64

In [134]:
df.shape

(3, 3)

In [135]:
df.info

<bound method DataFrame.info of    Country    Capital  Population
0  Belgium   Brussels     1118485
1    India  New Delhi  1387687867
2   Brazil   Brasilia   207465646>

In [136]:
data = {'a': [12, 21, 33],
       'b': [5, 2, 13],
       'c': [11, 13, 20]}
df = pd.DataFrame(data,
                 columns=['a', 'b', 'c'])

In [137]:
df

a   b   c
0  12   5  11
1  21   2  13
2  33  13  20

In [138]:
df>10

a      b     c
0  True  False  True
1  True  False  True
2  True   True  True

In [140]:
df['a'].mean()

22.0

In [148]:
df.iloc[1,1]

2

In [155]:
df.iloc[0,0]=13
df

a   b   c
0  13   5  11
1  21   2  13
2  33  13  20

In [157]:
(df>10).any()

a    True
b    True
c    True
dtype: bool

In [160]:
#select columns with any value less than 13
df.loc[:,(df<13).any()]

b   c
0   5  11
1   2  13
2  13  20

In [161]:
df.loc[:,[True, False, False]]

a
0  13
1  21
2  33

In [162]:
df

a   b   c
0  13   5  11
1  21   2  13
2  33  13  20

In [164]:
df[df['a']==21]

a  b   c
1  21  2  13

In [166]:
'b,c'.split(',')

['b', 'c']

In [167]:
df['b,c'.split(',')].values

array([[ 5, 11],
       [ 2, 13],
       [13, 20]])

In [168]:
df

a   b   c
0  13   5  11
1  21   2  13
2  33  13  20

In [172]:
for row,items in df.iterrows():
    print(row,items)

0 a    13
b     5
c    11
Name: 0, dtype: int64
1 a    21
b     2
c    13
Name: 1, dtype: int64
2 a    33
b    13
c    20
Name: 2, dtype: int64


In [175]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [176]:
df

a   b   c
0  13   5  11
1  21   2  13
2  33  13  20

In [179]:
df2=df.reindex(range(4), method='ffill')

In [180]:
df2.duplicated()

0    False
1    False
2    False
3     True
dtype: bool