## Given the data frame below, write a function that return the rows where the color is green or red and grade is above 90

In [1]:
import pandas as pd



data = {'Name': ['John','JT','Mario','Lance', 'Zara'],
        'Age': [21,30,43,33,23],
        'Color': ['Green','Blue','Red','Green', 'Red'],
        'Grade': [90,70,95,50,91]}

df = pd.DataFrame(data,
                  columns=['Name','Age','Color','Grade'])
df

Name  Age  Color  Grade
0   John   21  Green     90
1     JT   30   Blue     70
2  Mario   43    Red     95
3  Lance   33  Green     50
4   Zara   23    Red     91

In [9]:
# this is the core logic
df[((df['Color']=='Green') | (df['Color']=='Red')) & (df['Grade']>=90)]

Name  Age  Color  Grade
0   John   21  Green     90
2  Mario   43    Red     95
4   Zara   23    Red     91

In [10]:
def extractrows(df):
    """extracts rows where the color is green or red and grade is above 90"""
    return df[((df['Color']=='Green') | (df['Color']=='Red')) & (df['Grade']>=90)]


In [12]:
df2=extractrows(df)

In [13]:
df2

Name  Age  Color  Grade
0   John   21  Green     90
2  Mario   43    Red     95
4   Zara   23    Red     91

## Given the matrix below, find the transpose (without using built-in methods/functions)

In [15]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
rows=A.shape[0]
cols=A.shape[1]
# print(rows,cols)
B=np.zeros((cols,rows))
# print(B)
for col in range(cols):
    for row in range(rows):
        B[col,row]=A[row,col]

print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]


# What does this function will print

In [6]:
def what_is_it_that_i_actually_do(array1, d):
    temp=[]
    i=0
    n=len(array1)

    while (i<d):
        temp.append(array1[i])
        i=i+1

    i=0
    while (d<n):
        array1[i]=array1[d]
        d=d+1
        i=i+1
    
    return array1[:i]+temp

When we use the above function with the following inputs, what will be the output of this function:
what_is_it_that_i_actually_do([1,2,3,4,5,6,7], 2)

The solution is below but give it a try first. Remember, in a live coding interview you will have people watching you while you try to solve it, no time for google/stackoverflow :D, your time will be somewhat limited, you will feel the presure, and the stakes are usually quite high. I would suggest using the array provided and go through the function slowly and step by step, updating all variables along the way in a safe and organized way. Good luck! You can do it!

In [ ]:
# Lets create an array
array1 = [1,2,3,4,5,6,7]

temp=[]
i=0
# Lenght of this array will be 7
n=len(array1)
# This section appends the first i elements to temp
while (i<d):
    temp.append(array1[i])
    i=i+1
# This section does a shift to the left by d units   
i=0
while (d<n):
    array1[i]=array1[d]
    d=d+1
    i=i+1
# let us see what is on the outputs
print(temp)
print(array1)
print(array1[:i]+temp)